[env]
TERM = "xterm-256color"

[general]
import = [ 
#"~/.config/alacritty/catppuccin-frappe.toml" 
"~/.config/alacritty/catppuccin-macchiato.toml" 
#"~/.config/alacritty/catppuccin-mocha.toml" 
]

[font]
size = 12

[font.normal]
family = "JetbrainsMono Nerd Font"

[window]
padding.x = 20
padding.y = 20
